# - Document: <https://netpyoung.github.io/NF.Tool.ReleaseNoteMaker/>
# - News Fragment: {Maker.Directory}(/{Section.Path})/{IssueName}.{Type.Category}(.{RetryCount}).md
#   - example
#     - ChangeLog.d/1.added.md
#     - ChangeLog.d/SectionA/1.added.md

[ReleaseNote.Maker]
# Directory        = "ChangeLog.d"
# OutputFileName   = "CHANGELOG.md"
# TemplateFilePath = "ChangeLog.d/Template.tt"
# Name             = ""
# Version          = ""
# CsprojPath       = ""
# Ignores          = []
# OrphanPrefix     = "+"
# IssuePattern     = ""
# IssueFormat      = ""
# TitleFormat      = ""
# StartString      = "<!-- release notes start -->\n";
# IsWrap           = false
# IsAllBullets     = false
# IsSingleFile     = true
# EndOfLine        = "LF" # LF | CRLF | ENVIRONMENT

[ReleaseNote.Reader]
# VersionPattern = "(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?"
# TitlePattern = "^## .*(?<version>{VersionPattern})"

[[ReleaseNote.Section]]
Path = ""
DisplayName = "Main"

# [[ReleaseNote.Section]]
# Path = "SectionA"
# DisplayName = "Section A"

[[ReleaseNote.Type]]
Category = "feature"
DisplayName = "Features"
IsShowContent = true

[[ReleaseNote.Type]]
Category = "added"
DisplayName = "Added"
IsShowContent = true

[[ReleaseNote.Type]]
Category = "removed"
DisplayName = "Removed"
IsShowContent = true

[[ReleaseNote.Type]]
Category = "changed"
DisplayName = "Changed"
IsShowContent = true

[[ReleaseNote.Type]]
Category = "deprecated"
DisplayName = "Deprecated"
IsShowContent = true

[[ReleaseNote.Type]]
Category = "fixed"
DisplayName = "Fixed"
IsShowContent = true

[[ReleaseNote.Type]]
Category = "security"
DisplayName = "Security"
IsShowContent = true
